clang-tidy: Fix bugprone-move-forwarding-reference error
/ci_container_base/include/mp/type-interface.h:47:75: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
https://cirrus-ci.com/task/6187773452877824?logs=ci#L4712

Error was caused by mp/type-interface.h CustomBuildField field using std::move
instead of std::forward.

This commit:

- Adds std::forward and std::move several places to preserve lvalue/rvalue
  status.

- Defines a FunctionTraits::Fwd<...>(...) helper which does same thing as
  std::forward except it takes parameter number instead of a parameter type so
  generated code doesn't need as verbose as std::forward calls would be.

- Changes C++ code generator to pass arguments as `M0::Fwd<1>(arg1)` instead of
  `arg1` in generated code. This change can be verified by diffing a generated
  file like build/src/ipc/capnp/mining.capnp.proxy-client.c++ in the bitcoin
  build before and after this change.

Unlike the previous commit which resolved bugprone-move-forwarding-reference
errors by just switching std::move to std::forward, this commit required more
changes because just switching from std::move to std::forward in the
type-interface.h CustomBuildField function would lead to another error in the
CustomMakeProxyServer function there which is expecting an rvalue, not an
lvalue.

That error could have alternately been fixed by changing CustomMakeProxyServer
to accept lvalues and copy the shared_ptr. But this would be slightly less
efficient and it is better to resolve the problem at the root and just use
perfect forwarding everywhere, all the way up the call stack. This required the
changes to the code generator and clientInvoke described above.